# https://taskfile.dev

version: "3"

tasks:
  test:
    cmds:
      - go test -v ./...

  build:
    cmds:
      - go build -o "{{.USER_WORKING_DIR}}/bin/file-guard" ./file-guard/...
    silent: false
